sudo: required
language: generic

services:
    - docker
before_install:
    - docker build -t compiler .
    - docker run compiler /bin/sh -c "make test"
script:
    - docker ps -a | grep -q compiler
