language: c
cache: apt
sudo: required
addons:
    apt:
        sources:
            - avsm
        packages:
            - ocaml
            - ocaml-native-compilers
            - camlp4-extra
            - opam
env:
    - OPAMYES=1 OPAMVERBOSE=1
before-install:
    - ocaml -version
    - opam --version
install:
    - opam init
    - opam install ocamlfind menhir
    - eval `opam config env`
script:
    - make test
